ktor {
    deployment {
        port = 1234
        port = ${?PORT}
        host = "0.0.0.0"
        host = ${?HOST}
    }
    application {
        modules = [ com.decksolutions.kotlinbackendskeleton.ApplicationKt.module ]
    }
}